name: 'Build Package Action'
description: 'Build package'

inputs:
  package:
    description: 'Package name'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Building Docker image for ${{ inputs.package }}
      run: |
        cd packages/${{ inputs.package }}
        docker build .
      shell: bash
