name: 'Build Package Action'
description: 'Build package'

inputs:
  package:
    description: 'Package name'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - run: cd packages/${{ inputs.package }}
      shell: bash
    - run: docker build .
      shell: bash
