name: Build, test and deploy package

on:
  workflow_call:
    inputs:
      package:
        description: 'Package name to be build, test and deployed.'
        type: string
        required: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linted" >> $GITHUB_STEP_SUMMARY

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Get version
        id: version
        run: |
          cd packages/${{ inputs.package }}
          version=$(jq -r '.version' ./package.json)
          echo "version is $version"
          echo "version=$version" >> $GITHUB_OUTPUT
      - run: env
      - name: Building Docker image for ${{ inputs.package }}
        id: docker
        run: |
          imagePath="$RUNNER_TEMP/image.tar"
          echo "imagePath=$imagePath" | tee $GITHUB_OUTPUT
          cd packages/${{ inputs.package }}
          docker build -o "type=tar,dest=$imagePath" .
          echo "Files in temporary directory $RUNNER_TEMP"
          ls "$RUNNER_TEMP"
      - uses: actions/upload-artifact@v3
        with: 
          name: ${{ inputs.package }}-${{ steps.version.outputs.version }}
          path: ${{ steps.docker.outputs.imagePath }}

  Test:
    runs-on: ubuntu-latest
    needs: [ Lint ]
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: version
        run: |
          cd packages/${{ inputs.package }}
          version=$(jq -r '.version' ./package.json)
          echo "version=$version" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v3
        with: 
          name: ${{ inputs.package }}-${{ steps.version.outputs.version }}
          path: /tmp/image.tar
      - run: echo "Tests OK" >> $GITHUB_STEP_SUMMARY

  Deploy:
    runs-on: ubuntu-latest
    needs: [ Build, Test ]
    steps:
      - run: echo "Deployed" >> $GITHUB_STEP_SUMMARY
