name: CICD Package API

on:
  push:
    branches: [ main ]
    paths: 
      - 'packages/api/**'
      - 'packages/shared/**'
  workflow_dispatch:

env:
  PACKAGE: api
    
jobs:
  Build-Test-Deploy:
    uses: ./.github/workflows/cicd_build-test-deploy.yml
    with:
      package: ${{ PACKAGE }}

  # Build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/build-package
  #       with: 
  #         package: ${{ env.PACKAGE }}
  # Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Tests OK" >> $GITHUB_STEP_SUMMARY
  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: [ Build, Test ]
  #   steps:
  #     - run: echo "Deployed" >> $GITHUB_STEP_SUMMARY
