name: CICD Package API

on:
  push:
    branches: [ main ]
    paths: 
      - 'packages/api/**'
      - 'packages/shared/**'
  workflow_dispatch:

env:
  PACKAGE: api
    
jobs:
  Package:
    uses: ./.github/workflows/cicd_build-test-deploy.yml
    with:
      package: api
