name: CICD Package Frontend

on:
  push:
    branches: [ main ]
    paths: 
      - 'packages/frontend/**'
      - 'packages/shared/**'
  workflow_dispatch:

jobs:
  Package:
    uses: ./.github/workflows/cicd_build-test-deploy.yml
    with:
      package: frontend
  