name: CI/CD Package Service

on:
  push:
    branches: [ main ]
    paths: 
      - 'packages/service/**'

  workflow_dispatch:

jobs:
  Package:
    uses: ./.github/workflows/shared-build-test-deploy.yml
    with:
      package: service
    