name: CICD Package API

on:
  push:
    branches: [ main ]
    paths: 
      - 'packages/api/**'
      - 'packages/shared/**'
  workflow_dispatch:
    
jobs:
  Package:
    uses: ./.github/workflows/shared-build-test-deploy.yml
    with:
      package: api
